INSERT INTO USER(ID,NAME,AGE) VALUES('1', 'user1', 21);
INSERT INTO USER(ID,NAME,AGE) VALUES('2', 'user2', 22);
INSERT INTO USER(ID,NAME,AGE) VALUES('3', 'user3', 23);
INSERT INTO USER(ID,NAME,AGE) VALUES('4', 'user4', 24);